  #'  ============================================
  #'  Covariate extraction for telemetry locations
  #'  Washington Predator-Prey Project
  #'  Sarah Bassing
  #'  January 2022
  #'  ============================================
  #'  Script to extract covariate data at each GPS collar location and interpolated
  #'  locations based on the crawlWrap function. 
  #'  Relevant covariates include:
  #'    -Terrain Ruggedness Index (TRI; 30m res)
  #'    -Habitat openness (30m res)
  #'    -NDVI and maximum NDVI (250m, 16day res)
  #'    -Snow cover (derived from GEE snow on and snow disappearance dates; 500m, daily res)
  #'    -Distance to nearest road (30m res)
  #'    -Prey distributions (30m res)
  #'    -Predator distributions (30m res)
  #'  
  #'  NDVI and maximum NDVI covariates extracted using the rgee package & Google 
  #'  Earth Engine (GEE) with the rgee_Covariate_Extraction.R script. Snow 
  #'  Disappearance Date & Snow On Date rasters were generated using GEE and 
  #'  scripts provided by T.Ganz & K.Breen. Snow Disappearance Date script adapted
  #'  from code written & edited by R.Crumley (2019) & E.Mar (2018), and based on
  #'  Nolin et al 2021. Snow On Date script adapted from GEE code based on 
  #'  https://developers.google.com/earth-engine/tutorials/community/identifying-first-day-no-snow
  #'  Distance to nearest road raster was generated by T.Ganz in ArcGIS using 
  #'  the Cascadia Biodiversity Watch roads layer. Habitat openness raster was
  #'  generated using the Cascadia Biodiveristy Watch landcover type raster. 
  #'  Predator and prey distribution rasters were generated by estimating species- 
  #'  and season-specific RSFs and predicting relative probability of selection
  #'  across study areas per year with the Resource_Selection_Function_Models.R script. 
  #'  Covariates informing RSFs are different than those included here.
  #'  ============================================
  
  #'  Clean workspace
  rm(list = ls())
  
  #'  Load libraries
  library(sf)
  library(stars)
  library(rgeos)
  library(raster)
  library(terra)
  library(parallel)
  library(doParallel)
  library(future.apply)
  library(tidyverse)
  
  #'  Load crwOut animal location data for each species (takes a hot minute)
  load("./Outputs/Telemetry_crwOut/crwOut_ALL_2022-02-03.RData") #2021-12-08
  
  #'  Read in previously extracted NDVI data from GEE
  #'  Note: NDVIsmr is for summer locs ONLY, NDVImax is for winter locs ONLY
  load("./Outputs/Telemetry_covs/ee_NDVIsmr_list_2022-01-08.RData")
  load("./Outputs/Telemetry_covs/ee_NDVImax_list_2022-01-08.RData")
  
  #'  Read in spatial data
  TRI <- rast("./Shapefiles/WA DEM rasters/WPPP_TRI.tif")
  dist2Road_major <- rast("./Shapefiles/Cascadia_layers/roadsForTaylor/WPPP_dist_to_major_rds_2855.tiff")
  dist2Road_minor <- rast("./Shapefiles/Cascadia_layers/roadsForTaylor/WPPP_dist_to_minor_rds_2855.tiff")
  percopen18 <- rast("./Shapefiles/Cascadia_layers/PercOpen18.tif")
  percopen19 <- rast("./Shapefiles/Cascadia_layers/PercOpen19.tif")
  percopen20 <- rast("./Shapefiles/Cascadia_layers/PercOpen20.tif")
  snow_on18 <- rast("./Shapefiles/Snow/SOD_WPPP_2018_500m.tif")
  snow_on19 <- rast("./Shapefiles/Snow/SOD_WPPP_2019_500m.tif")
  snow_on20 <- rast("./Shapefiles/Snow/SOD_WPPP_2020_500m.tif")
  # snow_on21 <- rast("./Shapefiles/Snow/SOD_WPPP_2021_500m.tif")
  snow_off1819 <- rast("./Shapefiles/Snow/SDD2019_WPPP_500m.tif")
  snow_off1920 <- rast("./Shapefiles/Snow/SDD2020_WPPP_500m.tif")
  snow_off2021 <- rast("./Shapefiles/Snow/SDD2021_WPPP_500m.tif")
  #'  RSFs: stack of 3 rasters, 1 per year
  md_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/md_smr_RSFstack.tif") 
  md_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/md_wtr_RSFstack.tif")
  elk_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/elk_smr_RSFstack.tif")
  elk_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/elk_wtr_RSFstack.tif")
  wtd_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/wtd_smr_RSFstack.tif")
  wtd_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/wtd_wtr_RSFstack.tif")
  coug_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/coug_smr_RSFstack.tif")
  coug_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/coug_wtr_RSFstack.tif")
  wolf_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/wolf_smr_RSFstack.tif")
  wolf_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/wolf_wtr_RSFstack.tif")
  bob_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/bob_smr_RSFstack.tif")
  bob_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/bob_wtr_RSFstack.tif")
  coy_smr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/coy_smr_RSFstack.tif")
  coy_wtr_rsf <- rast("./Shapefiles/Predicted_RSFs/Predicted_RSF_Jan25_nonbinned/coy_wtr_RSFstack.tif")
  
  #'  Identify projections & resolutions of spatial layers
  crs(TRI, describe=TRUE, proj=TRUE) #projection(tri)
  crs(dist2Road_major, describe=TRUE, proj=TRUE) #projection(dist2Road_major)
  crs(percopen18, describe=TRUE, proj=TRUE) #projection(percopen18)
  crs(snow_on18, describe=TRUE, proj=TRUE) # projection(snow_on18)
  crs(snow_off1819, describe=TRUE, proj=TRUE) #projection(snow_off1819)
  crs(md_smr_rsf, describe=TRUE, proj=TRUE) #projection(md_smr_rsf)
  
  res(TRI)
  res(dist2Road_major)
  res(percopen18)
  res(snow_on18)
  res(snow_off1819)
  res(md_smr_rsf)
  
  #'  Stack similar covariate rasters (use c() to stack with the terra package)
  road_stack <- c(dist2Road_major, dist2Road_minor)
  open_stack <- c(percopen18, percopen19, percopen20)
  snowOn_stack <- c(snow_on18, snow_on19, snow_on20) #, snow_on21
  snowOff_stack <- c(snow_off1819, snow_off1920, snow_off2021)
  
  #'  Define projections based on raster projections
  sa_proj <- projection("EPSG:2855")
  wgs84 <- projection("+proj=longlat +datum=WGS84 +no_defs")
  
  #'  Make crwOut data spatial sf objects
  spatial_locs <- function(locs) {
    move <- locs[[2]]
    sf_locs <- st_as_sf(move, coords = c("mu.x", "mu.y"), crs = sa_proj) %>%
      mutate(obs = seq(1:nrow(.))) %>%
      dplyr::select(c("ID", "FullID", "Sex", "Season", "StudyArea", "AnimalID", "time", "obs")) %>%
      #'  Fill in missing values for AnimalID, etc. where locations interpolated
      fill(FullID, .direction = "down") %>%
      fill(Sex, .direction = "down") %>%
      fill(Season, .direction = "down") %>%
      fill(StudyArea, .direction = "down") %>%
      fill(AnimalID, .direction = "down")
    return(sf_locs)
  }
  sf_locs <- lapply(crwOut_ALL, spatial_locs)
  
  #' #'  Reproject sf objects to match WGS84 rasters
  #' sf_reproj <- function(locs) {
  #'   locs_wgs84 <- st_transform(locs, crs = wgs84)
  #'   return(locs_wgs84)
  #' }
  #' sf_locs_wgs84 <- lapply(sf_locs, sf_reproj)
  #' 
  #' tst <- sf_locs[[10]]
  #' tst_wgs84 <- sf_locs_wgs84[[10]]
  
  #'  Reformat NDVI data so they have matching columns
  #'  Summer NDVI values
  NDVIsmr <- function(NDVIsmr) {
    NDVIsmr <- transmute(NDVIsmr, obs = ID, AnimalID = AnimalID, Season = Season, 
                         StudyArea = StudyArea, time = times, NDVI = NDVI) %>%
      mutate(time = as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S", tz = "Etc/GMT+8"))
    return(NDVIsmr)
  }
  NDVIsmr <- lapply(ee_NDVIsmr_list, NDVIsmr)
  #'  Max NDVI  values at winter locations
  NDVImax <- function(NDVImax) {
    NDVImax <- transmute(NDVImax, obs = ID, AnimalID = AnimalID, Season = Season, 
                         StudyArea = StudyArea, time = times, NDVI = maxNDVI) %>%
      mutate(time = as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S", tz = "Etc/GMT+8"))
    return(NDVImax)
  }
  NDVImax <- lapply(ee_NDVImax_list, NDVImax)
  
  #'  Split seasonal NDVI data by study area
  #'  NOTE: ELK & WTD lists will be empty after NDVI_OK & MD lists will be empty after NDVI_NE
  #'  Okanogan summer & max NDVI values
  NDVI_OK <- function(ndvi){
    OK_only <- ndvi[ndvi$StudyArea == "OK",]
    return(OK_only)
  }
  NDVIsmr_OK <- lapply(NDVIsmr, NDVI_OK)
  NDVImax_OK <- lapply(NDVImax, NDVI_OK)
  #'  Northeast summer & max NDVI values
  NDVI_NE <- function(ndvi){
    NE_only <- ndvi[ndvi$StudyArea == "NE",]
    return(NE_only)
  }
  NDVIsmr_NE <- lapply(NDVIsmr, NDVI_NE)
  NDVImax_NE <- lapply(NDVImax, NDVI_NE)
  
  
  #'  -------------------------------------------
  ####  COVARIATE EXTRACTION & CALCULATIONS  ####
  #'  -------------------------------------------
  #'  Takes forever but running in parallel helps 
  
  #'  Monitor time
  start.time <- Sys.time()

  #' #'  Setup script to run in parallel
  #' #'  Extract covariates for each species at once
  #' #'  Identify how many cores I want to use
  #' detectCores(logical = FALSE)
  #' cl <- parallel::makeCluster(4)  # change to 14 when working correctly on lab computer
  #' #'  Run in parallel on local computer with specified number of cores
  #' plan(cluster, workers = cl)

  #'  Master function to extract and manipulate covariate data for each species
  cov_extract <- function(locs) { 
    
    #'  Reproject sf objects to match WGS84 rasters to match certain rasters
    locs_wgs84 <- st_transform(locs, crs = wgs84)
    
    #'  --------------------------------------------------
    ####  1. Extract data from habitat and road rasters  #### 
    #'  --------------------------------------------------
    #'  Note: most of these are stacked rasters, 1 raster per year
    #'  Be sure to match data and raster projections
    #'  FYI: Terra package MUCH faster than Raster package for this many locations
    #'  Extract from terra package requires location data be vectorized (vect())
    tri <- terra::extract(TRI, vect(locs_wgs84)) %>% 
      transmute(obs = ID, TRI = WPPP_TRI)
    dist2Road <- terra::extract(road_stack, vect(locs))
    #'  Find distance to nearest road between major and minor roadways- takes a minute
    #'  apply min function row-wise (1 = across each row), excluding 1st column of df
    dist2Road$NearestRd <- apply(dist2Road[-1], 1, min)
    dist2Road <- transmute(dist2Road, obs = ID, Dist2Road = NearestRd)
    percopen <- terra::extract(open_stack, vect(locs_wgs84)) %>%
      transmute(obs = ID, PercOpen18 = PercOpen18, PercOpen19 = PercOpen19, PercOpen20 = PercOpen20) %>%
      full_join(locs, by = "obs") %>%
      mutate(
        PercOpen = ifelse(Season == "Summer18", PercOpen18, PercOpen20),
        PercOpen = ifelse(Season == "Summer19", PercOpen19, PercOpen),
        PercOpen = ifelse(Season == "Winter1819", PercOpen18, PercOpen),
        PercOpen = ifelse(Season == "Winter1920", PercOpen19, PercOpen)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, PercOpen)) 

    
    #'  ----------------------------------------------------------------
    ####  2. Extract data from snow-on and snow-disappearance rasters  ####
    #'  ----------------------------------------------------------------
    #'  Need to extract snow-on and snow-off dates for each location, then compare
    #'  this period of snow cover to timing of animal location and determine if
    #'  there was > 0% snow cover at the location when the animal was present.
    
    #'  Snow-On-Date (based on first day looking backwards from Dec. 31 that 
    #'  pixel has 0% snow cover)
    snowon <- terra::extract(snowOn_stack, vect(locs_wgs84)) 
    names(snowon) <- c("obs", "calDoy18", "calDoy19", "calDoy20") 
    snowon <- snowon %>%
      mutate(
        #'  Some snow-on observations are "zero" due to MODIS masking cloud cover, etc. 
        #'  Apply a location's mean calDoy using rowMean across the three years 
        #'  of sampling when observation is missing (0) for a single year 
        calDoy18 = ifelse(calDoy18 == 0, round(rowMeans(snowon[,c(3:4)], na.rm = TRUE), 0), calDoy18),
        calDoy19 = ifelse(calDoy19 == 0, round(rowMeans(snowon[,c(2,4)], na.rm = TRUE), 0), calDoy19),
        calDoy20 = ifelse(calDoy20 == 0, round(rowMeans(snowon[,c(2:3)], na.rm = TRUE), 0), calDoy20),
        #'  Change 0s to NAs so missing observations don't bias averaging below
        calDoy18 = ifelse(calDoy18 == 0, NA, calDoy18),
        calDoy19 = ifelse(calDoy19 == 0, NA, calDoy19),
        calDoy20 = ifelse(calDoy20 == 0, NA, calDoy20))
    #'  Apply annual mean calDoy using colMeans (& round to nearest whole number) 
    #'  when calDoy is masked across all years (all 0s) 
    #'  FYI, colMean includes missing observations in averaging if this step is
    #'  done in the same mutate command above. So annoying!
    snowon <- snowon %>%
      mutate(
        SnowOn18 = ifelse(is.na(calDoy18), round(colMeans(snowon[c("calDoy18")], na.rm = TRUE), 0), calDoy18),
        SnowOn19 = ifelse(is.na(calDoy19), round(colMeans(snowon[c("calDoy19")], na.rm = TRUE), 0), calDoy19),
        SnowOn20 = ifelse(is.na(calDoy20), round(colMeans(snowon[c("calDoy20")], na.rm = TRUE), 0), calDoy20),
        #'  calDoy represents the last julian day with NO snow (origin day is Jan. 1)
        #'  Need to add 1 to calDoy to represent first julian day WITH > 0% snow
        SOD18 = SnowOn18 + 1,
        SOD19 = SnowOn19 + 1,
        SOD20 = SnowOn20 + 1, 
        #'  Convert SOD (days since Jan. 1) to actual dates
        #'  Make into character b/c ifelse below does odd formatting otherwise
        SOD18_Date = as.character(as.Date(SOD18, origin = "2018-01-01")),
        SOD19_Date = as.character(as.Date(SOD19, origin = "2019-01-01")),
        SOD20_Date = as.character(as.Date(SOD20, origin = "2020-01-01"))) 

    #'  Snow-Disappearance-Date (first julian day moving forward where pixel had
    #'  0% snow cover, origin day is Oct. 1 based on "Water Year")
    snowoff <- terra::extract(snowOff_stack, vect(locs_wgs84))
    names(snowoff) <- c("obs", "SDD1819", "SDD1920", "SDD2021")
    snowoff <- snowoff %>%
      mutate(
        #'  Some snow disappearance dates are missing due to MODIS masking cloud cover, etc.
        #'  Change 0s to NAs so missing observations don't bias averaging below
        SDD1819 = ifelse(SDD1819 == 0, NA, SDD1819),
        SDD1920 = ifelse(SDD1920 == 0, NA, SDD1920),
        SDD2021 = ifelse(SDD2021 == 0, NA, SDD2021))
    #'  Apply annual mean calDoy using colMeans (& round to nearest whole number) 
    #'  to observations where calDoy was masked. Not using row-wise averages for 
    #'  a given location like above b/c many observations were missing for 2 years 
    #'  which biases row-wise average low using rowMeans.
    #'  FYI, colMean includes missing observations in averaging if this step is
    #'  done in the same mutate command above. So annoying!
    snowoff <- snowoff %>%
      mutate(
        SnowOff1819 = ifelse(is.na(SDD1819), round(colMeans(snowoff[c("SDD1819")], na.rm = TRUE), 0), SDD1819),
        SnowOff1920 = ifelse(is.na(SDD1920), round(colMeans(snowoff[c("SDD1920")], na.rm = TRUE), 0), SDD1920),
        SnowOff2021 = ifelse(is.na(SDD2021), round(colMeans(snowoff[c("SDD2021")], na.rm = TRUE), 0), SDD2021),
        #'  Convert SDD (days since Oct. 1) to actual dates
        #'  Note origin date is start of "Water Year", not January 1
        #'  Make into character b/c ifelse below does odd formatting otherwise
        SDD1819_Date = as.character(as.Date(SnowOff1819, origin = "2018-10-01")),
        SDD1920_Date = as.character(as.Date(SnowOff1920, origin = "2019-10-01")),
        SDD2021_Date = as.character(as.Date(SnowOff2021, origin = "2020-10-01"))) 
      
    #'  Identify whether there was > 0% snow cover at each animal location
    snowcover <- snowon %>%
      full_join(snowoff, by = "obs") %>%
      #'  Save only dates and arrange by snow on & disappearance dates per year
      dplyr::select(c(obs, SOD18_Date, SDD1819_Date, SOD19_Date, SDD1920_Date,
                      SOD20_Date, SDD2021_Date)) %>%
      #'  Join with crwOut data
      full_join(locs, by = "obs") %>% 
      mutate(
        Date = as.Date(time, tz = "America/Los_Angeles"),
        #'  Create single column for snow-on dates across years
        SOD = ifelse(Season == "Summer18", SOD18_Date, SOD20_Date), # don't actually need Snow for summer locs but helpful for column book-keeping
        SOD = ifelse(Season == "Summer19", SOD19_Date, SOD),        # don't actually need Snow for summer locs but helpful for column book-keeping
        SOD = ifelse(Season == "Winter1819", SOD18_Date, SOD),
        SOD = ifelse(Season == "Winter1920", SOD19_Date, SOD),
        SOD = as.Date(SOD, format = "%Y-%m-%d"),
        #'  Create single column for snow-disappearance dates across years
        SDD = ifelse(Season == "Summer18", SDD1819_Date, SDD2021_Date), # don't actually need Snow for summer locs but helpful for column book-keeping
        SDD = ifelse(Season == "Summer19", SDD1920_Date, SDD),          # don't actually need Snow for summer locs but helpful for column book-keeping
        SDD = ifelse(Season == "Winter1819", SDD1819_Date, SDD),
        SDD = ifelse(Season == "Winter1920", SDD1920_Date, SDD),
        SDD = as.Date(SDD, format = "%Y-%m-%d"),
        #'  Indicate if location Date falls between snow-on & snow-disappearance date
        SnowCover = ifelse(Date >= SOD & Date < SDD, 1, 0)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, SOD, Date, SDD, SnowCover))
    
    
    #'  ----------------------------------------------------------
    ####  3. Species and season specific RSFs (stacked by year)  ####
    #'  ----------------------------------------------------------
    #'  Note: NAs arise for locations if RSF is specific to only one study area
    
    ####  MULE DEER  ####
    md_smr <- terra::extract(md_smr_rsf, vect(locs))
    names(md_smr) <- c("obs", "MD_smr18", "MD_smr19", "MD_smr20")
    md_wtr <- terra::extract(md_wtr_rsf, vect(locs))
    names(md_wtr) <- c("obs", "MD_wtr1819", "MD_wtr1920", "MD_wtr2021")
    md_rsf <- full_join(md_smr, md_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        MD_smr = ifelse(Season == "Summer18", MD_smr18, MD_smr20),
        MD_smr = ifelse(Season == "Summer19", MD_smr19, MD_smr),
        MD_wtr = ifelse(Season == "Winter1819", MD_wtr1819, MD_wtr2021),
        MD_wtr = ifelse(Season == "Winter1920", MD_wtr1920, MD_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, MD_smr, MD_wtr)) 
    ####  ELK  ####
    elk_smr <- terra::extract(elk_smr_rsf, vect(locs))
    names(elk_smr) <- c("obs", "ELK_smr18", "ELK_smr19", "ELK_smr20")
    elk_wtr <- terra::extract(elk_wtr_rsf, vect(locs))
    names(elk_wtr) <- c("obs", "ELK_wtr1819", "ELK_wtr1920", "ELK_wtr2021")
    elk_rsf <- full_join(elk_smr, elk_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        ELK_smr = ifelse(Season == "Summer18", ELK_smr18, ELK_smr20),
        ELK_smr = ifelse(Season == "Summer19", ELK_smr19, ELK_smr),
        ELK_wtr = ifelse(Season == "Winter1819", ELK_wtr1819, ELK_wtr2021),
        ELK_wtr = ifelse(Season == "Winter1920", ELK_wtr1920, ELK_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, ELK_smr, ELK_wtr)) 
    ####  WHITE-TAILED DEER  ####
    wtd_smr <- terra::extract(wtd_smr_rsf, vect(locs))
    names(wtd_smr) <- c("obs", "WTD_smr18", "WTD_smr19", "WTD_smr20")
    wtd_wtr <- terra::extract(wtd_wtr_rsf, vect(locs))
    names(wtd_wtr) <- c("obs", "WTD_wtr1819", "WTD_wtr1920", "WTD_wtr2021")
    wtd_rsf <- full_join(wtd_smr, wtd_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        WTD_smr = ifelse(Season == "Summer18", WTD_smr18, WTD_smr20),
        WTD_smr = ifelse(Season == "Summer19", WTD_smr19, WTD_smr),
        WTD_wtr = ifelse(Season == "Winter1819", WTD_wtr1819, WTD_wtr2021),
        WTD_wtr = ifelse(Season == "Winter1920", WTD_wtr1920, WTD_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, WTD_smr, WTD_wtr)) 
    ####  COUGAR  ####
    coug_smr <- terra::extract(coug_smr_rsf, vect(locs))
    names(coug_smr) <- c("obs", "COUG_smr18", "COUG_smr19", "COUG_smr20")
    coug_wtr <- terra::extract(coug_wtr_rsf, vect(locs))
    names(coug_wtr) <- c("obs", "COUG_wtr1819", "COUG_wtr1920", "COUG_wtr2021")
    coug_rsf <- full_join(coug_smr, coug_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        COUG_smr = ifelse(Season == "Summer18", COUG_smr18, COUG_smr20),
        COUG_smr = ifelse(Season == "Summer19", COUG_smr19, COUG_smr),
        COUG_wtr = ifelse(Season == "Winter1819", COUG_wtr1819, COUG_wtr2021),
        COUG_wtr = ifelse(Season == "Winter1920", COUG_wtr1920, COUG_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, COUG_smr, COUG_wtr)) 
    ####  WOLF  ####
    wolf_smr <- terra::extract(wolf_smr_rsf, vect(locs))
    names(wolf_smr) <- c("obs", "WOLF_smr18", "WOLF_smr19", "WOLF_smr20")
    wolf_wtr <- terra::extract(wolf_wtr_rsf, vect(locs))
    names(wolf_wtr) <- c("obs", "WOLF_wtr1819", "WOLF_wtr1920", "WOLF_wtr2021")
    wolf_rsf <- full_join(wolf_smr, wolf_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        WOLF_smr = ifelse(Season == "Summer18", WOLF_smr18, WOLF_smr20),
        WOLF_smr = ifelse(Season == "Summer19", WOLF_smr19, WOLF_smr),
        WOLF_wtr = ifelse(Season == "Winter1819", WOLF_wtr1819, WOLF_wtr2021),
        WOLF_wtr = ifelse(Season == "Winter1920", WOLF_wtr1920, WOLF_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, WOLF_smr, WOLF_wtr)) 
    ####  BOBCAT  ####
    bob_smr <- terra::extract(bob_smr_rsf, vect(locs))
    names(bob_smr) <- c("obs", "BOB_smr18", "BOB_smr19", "BOB_smr20")
    bob_wtr <- terra::extract(bob_wtr_rsf, vect(locs))
    names(bob_wtr) <- c("obs", "BOB_wtr1819", "BOB_wtr1920", "BOB_wtr2021")
    bob_rsf <- full_join(bob_smr, bob_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        BOB_smr = ifelse(Season == "Summer18", BOB_smr18, BOB_smr20),
        BOB_smr = ifelse(Season == "Summer19", BOB_smr19, BOB_smr),
        BOB_wtr = ifelse(Season == "Winter1819", BOB_wtr1819, BOB_wtr2021),
        BOB_wtr = ifelse(Season == "Winter1920", BOB_wtr1920, BOB_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, BOB_smr, BOB_wtr)) 
    ####  COYOTE  ####
    coy_smr <- terra::extract(coy_smr_rsf, vect(locs))
    names(coy_smr) <- c("obs", "COY_smr18", "COY_smr19", "COY_smr20")
    coy_wtr <- terra::extract(coy_wtr_rsf, vect(locs))
    names(coy_wtr) <- c("obs", "COY_wtr1819", "COY_wtr1920", "COY_wtr2021")
    coy_rsf <- full_join(coy_smr, coy_wtr, by = "obs") %>%
      full_join(locs, by = "obs") %>%
      mutate(
        COY_smr = ifelse(Season == "Summer18", COY_smr18, COY_smr20),
        COY_smr = ifelse(Season == "Summer19", COY_smr19, COY_smr),
        COY_wtr = ifelse(Season == "Winter1819", COY_wtr1819, COY_wtr2021),
        COY_wtr = ifelse(Season == "Winter1920", COY_wtr1920, COY_wtr)
      ) %>%
      dplyr::select(c(obs, ID, AnimalID, Season, StudyArea, COY_smr, COY_wtr)) 
    
    
    #'  Join all extracted covariates together
    crwOut_covs <- full_join(tri, dist2Road, by = "obs") %>%
      full_join(percopen, by = "obs") %>%
      full_join(snowcover, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>% 
      full_join(md_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(elk_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(wtd_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(coug_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(wolf_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(coy_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(bob_rsf, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      full_join(locs, by = c("obs", "ID", "AnimalID", "Season", "StudyArea")) %>%
      dplyr::select(c("obs", "ID", "AnimalID", "Season", "StudyArea", "time", 
                      "Date", "Dist2Road", "PercOpen", "SnowCover", "TRI", "MD_smr",       
                      "MD_wtr", "ELK_smr", "ELK_wtr", "WTD_smr", "WTD_wtr",
                      "COUG_smr", "COUG_wtr", "WOLF_smr", "WOLF_wtr", "BOB_smr",
                      "BOB_wtr", "COY_smr", "COY_wtr"))

    return(crwOut_covs)
  }
  #'  Run list of species location data through function in parallel
  spp_telem_covs <- lapply(sf_locs, cov_extract) # non-parallel approach
  # spp_telem_covs <- future_lapply(sf_locs, cov_extract) 
  
  
  #'  End time keeping
  end.time <- Sys.time()
  #' #'  Stop running in parallel
  #' parallel::stopCluster(cl)
  #'  How long did this take?
  difftime(end.time, start.time, units = "hours")

  
  #'  List covariate data sets by season and study area (for predators)
  #'  Note the order: 1) MD smr, 2) MD wtr, 3) ELK smr, 4) ELK wtr, 5) WTD smr, 
  #'  6) WTD wtr, 7) COUG smr OK, 8) COUG wtr OK, 9) COUG smr NE, 10) COUG wtr NE, 
  #'  11) WOLF smr OK, 12) WOLF wtr OK, 13) WOLF smr NE, 14) WOLF wtr NE, 
  #'  15) BOB smr OK, 16) BOB wtr OK, 17) BOB smr NE, 18) BOB wtr NE, 19) COY smr OK, 
  #'  20) COY wtr OK, 21) COY smr NE, 22) COY wtr NE
  smr_covs <- list(spp_telem_covs[[1]], spp_telem_covs[[3]], spp_telem_covs[[5]], 
                   spp_telem_covs[[7]], spp_telem_covs[[9]], spp_telem_covs[[11]], 
                   spp_telem_covs[[13]], spp_telem_covs[[15]], spp_telem_covs[[17]], 
                   spp_telem_covs[[19]], spp_telem_covs[[21]])
  wtr_covs <- list(spp_telem_covs[[2]], spp_telem_covs[[4]], spp_telem_covs[[6]], 
                   spp_telem_covs[[8]], spp_telem_covs[[10]], spp_telem_covs[[12]], 
                   spp_telem_covs[[14]], spp_telem_covs[[16]], spp_telem_covs[[18]], 
                   spp_telem_covs[[20]], spp_telem_covs[[22]])
  
  #'  Remove summer/winter RSF values from winter/summer data sets, respectively.
  #'  Be aware there are some locations where landscape covariates were extracted
  #'  but missing RSF values b/c those locations were masked in the RSF analyses,
  #'  producing NAs for all RSF values at these locations
  remove_wtr_covs <- function(covs) {
    smr_data <- dplyr::select(covs, -c("MD_wtr", "ELK_wtr", "WTD_wtr", "COUG_wtr", 
                                           "WOLF_wtr", "BOB_wtr", "COY_wtr")) 
    names(smr_data) <- c("obs", "ID", "AnimalID", "Season", "StudyArea", "time", "Date", 
                     "Dist2Road", "PercOpen", "SnowCover", "TRI", "MD_RSF", "ELK_RSF", 
                     "WTD_RSF", "COUG_RSF", "WOLF_RSF", "BOB_RSF", "COY_RSF")
    return(smr_data)
  }
  smr_telem_data <- lapply(smr_covs, remove_wtr_covs)
  
  remove_smr_covs <- function(covs) {
    wtr_data <- dplyr::select(covs, -c("MD_smr", "ELK_smr", "WTD_smr", "COUG_smr",  
                                           "WOLF_smr", "BOB_smr", "COY_smr"))
    names(wtr_data) <- c("obs", "ID", "AnimalID", "Season", "StudyArea", "time", "Date", 
                     "Dist2Road", "PercOpen", "SnowCover", "TRI", "MD_RSF", "ELK_RSF", 
                     "WTD_RSF", "COUG_RSF", "WOLF_RSF", "BOB_RSF", "COY_RSF")
    return(wtr_data)
  }
  wtr_telem_data <- lapply(wtr_covs, remove_smr_covs)
  
  #'  Reorder NDVI lists to match species, season, & study area-specific covariate
  #'  lists --- KEEP TRACK OF THIS ORDER!!!!
  #'  NDVI_smr list order: 1) MD smr, 2) ELK smr, 3) WTD smr, 4) COUG smr OK,
  #'  5) COUG smr NE, 6) WOLF smr OK, 7) WOLF smr NE, 8) BOB smr OK, 9) BOB smr NE,
  #'  10) COY smr OK, 11) COY smr NE
  #'  NDVI_max list order: 1) MD wtr, 2) ELK wtr, 3) WTD wtr, 4) COUG wtr OK,
  #'  5) COUG wtr NE, 6) WOLF wtr OK, 7) WOLF wtr NE, 8) BOB wtr OK, 9) BOB wtr NE,
  #'  10) COY wtr OK, 11) COY wtr NE
  NDVI_smr <- list(NDVIsmr_OK[[1]], NDVIsmr_NE[[2]], NDVIsmr_NE[[3]], NDVIsmr_OK[[4]],
                   NDVIsmr_NE[[4]], NDVIsmr_OK[[5]], NDVIsmr_NE[[5]], NDVIsmr_OK[[6]],
                   NDVIsmr_NE[[6]], NDVIsmr_OK[[7]], NDVIsmr_NE[[7]])

  NDVI_max <- list(NDVImax_OK[[1]], NDVImax_NE[[2]], NDVImax_NE[[3]], NDVImax_OK[[4]],
                   NDVImax_NE[[4]], NDVImax_OK[[5]], NDVImax_NE[[5]], NDVImax_OK[[6]],
                   NDVImax_NE[[6]], NDVImax_OK[[7]], NDVImax_NE[[7]])

  #'  Add NDVI data to covariate data frames based on species and season
  #'  Remember: NDVIsmr are the spatio-temporally matched NDVI values for summer locs
  #'  NDVImax are the maximum NDVI value from previous growing season for each winter loc
  add_ndvi <- function(covs, ndvi) {
    full_covs <- full_join(covs, ndvi, by = c("AnimalID", "Season", "StudyArea", "time")) %>%
      relocate(NDVI, .after = Dist2Road) %>%
      dplyr::select(-obs.y)
    names(full_covs)[names(full_covs) == "obs.x"] <- "obs"
    return(full_covs)
  }
  #'  Append species and season specific NDVI data to covariate datasets
  #'  FYI: mapply allows each call of the add_ndvi function to get the 1st, 2nd,
  #'  3rd, etc. element of BOTH lists, SIMPLIFY keeps output in list format
  smr_cov_data <- mapply(add_ndvi, smr_telem_data, NDVI_smr, SIMPLIFY = FALSE)
  wtr_cov_data <- mapply(add_ndvi, wtr_telem_data, NDVI_max, SIMPLIFY = FALSE)
  
  #'  List covariates by study area
  #'  Include only species collared in respective study area
  #'  Okanogan: 1:2) MD, 3:4) COUG, 5:6) WOLF, 7:8) BOB, 9:10) COY
  OK_covs <- list(smr_cov_data[[1]], wtr_cov_data[[1]], smr_cov_data[[4]], wtr_cov_data[[4]],
                  smr_cov_data[[6]], wtr_cov_data[[6]], smr_cov_data[[8]], wtr_cov_data[[8]],
                  smr_cov_data[[10]], wtr_cov_data[[10]])
  #'  Northeast: 1:2) ELK, 3:4) WTD, 5:6) COUG, 7:8) WOLF, 9:10) BOB, 11:12) COY
  NE_covs <- list(smr_cov_data[[2]], wtr_cov_data[[2]], smr_cov_data[[3]], wtr_cov_data[[3]],
                  smr_cov_data[[5]], wtr_cov_data[[5]], smr_cov_data[[7]], wtr_cov_data[[7]],
                  smr_cov_data[[9]], wtr_cov_data[[9]], smr_cov_data[[11]], wtr_cov_data[[11]])
  
  #'  Remove MD & ELK/WTD data from NE & OK covariates, respectively
  #'  These columns of pure NAs will cause problems when merging covariate data
  #'  with crwOut data in HMM script
  #'  Remove RSF data for species collared only in NE from OK data sets
  nix_ELK_WTD <- function(OK_covs) {
    no_ELK_WTD <- dplyr::select(OK_covs, -c(ELK_RSF, WTD_RSF))
    return(no_ELK_WTD)
  }
  skinny_OK <- lapply(OK_covs, nix_ELK_WTD)
  #'  Remove RSF data for species collared only in OK from NE data sets
  nix_MD <- function(NE_covs) {
    no_MD <- dplyr::select(NE_covs, -c(MD_RSF))
    return(no_MD)
  }
  skinny_NE <- lapply(NE_covs, nix_MD)
  
  
  #'  Merge back into one giant list keeping track of list order!
  #'  1) MD smr OK,    2) MD wtr OK,    3) ELK smr NE,   4) ELK wtr NE,   5) WTD smr NE, 
  #'  6) WTD wtr NE,   7) COUG smr OK,  8) COUG wtr OK,  9) COUG smr NE,  10) COUG wtr NE, 
  #'  11) WOLF smr OK, 12) WOLF wtr OK, 13) WOLF smr NE, 14) WOLF wtr NE, 15) BOB smr OK,  
  #'  16) BOB wtr OK,  17) BOB smr NE,  18) BOB smr NE,  19) COY smr OK,  20) COY wtr OK, 
  #'  21) COY smr NE,  22) COY wtr NE
  spp_telem_covs <- list(skinny_OK[[1]], skinny_OK[[2]], skinny_NE[[1]], skinny_NE[[2]],
                         skinny_NE[[3]], skinny_NE[[4]], skinny_OK[[3]], skinny_OK[[4]], 
                         skinny_NE[[5]], skinny_NE[[6]], skinny_OK[[5]], skinny_OK[[6]],
                         skinny_NE[[7]], skinny_NE[[8]], skinny_OK[[7]], skinny_OK[[8]],
                         skinny_NE[[9]], skinny_NE[[10]], skinny_OK[[9]], skinny_OK[[10]],
                         skinny_NE[[11]], skinny_NE[[12]])

  
  #'  Save!
  save(spp_telem_covs, file = paste0("./Outputs/Telemetry_covs/spp_telem_covs_", Sys.Date(), ".RData"))


  
  
  
  
  